---
- hosts: veiled-haven.net
  become: true
  roles:
    - ansible-role-btrfs
    - Aisbergg.snapper
    - geerlingguy.docker
    - ansible-role-veiled-haven-landingpage
    - ansible-role-crafty
    - ansible-role-netdata
    - ansible-role-haproxy
    - ansible-role-certbot
    - ansible-role-certbot-hook

- hosts: mantikor
  become: true
  roles:
    - ansible-role-offsite-backup
